### ISSUE TITLE
Unable to install via dev tools

### ISSUE THREAD

**Issue by Oneiricer** [hrbrmstr/msgxtractr#12]
Hi
In R console i try to install this package, however it does not appear to work. Currently using 3.5.2 - do i need to downgrade my R?

```
>devtools::install_github("hrbrmstr/msgxtract
Downloading GitHub repo hrbrmstr/msgxtractr@master
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Command not found
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

```

**Comment by eladnoor** [comment]
Hi @hrbrmstr, I had exactly the same issue as @Oneiricer. I'm using a windows machine, and here is the session Info:

```
- Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows Server x64          
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  German_Switzerland.1252     
 ctype    German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2019-02-08                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.2)
 backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.2)
 callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.2)
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
 curl          3.3     2019-01-10 [1] CRAN (R 3.5.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.2)
 devtools    * 2.0.1   2018-10-26 [1] CRAN (R 3.5.2)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.2)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.2)
 packrat       0.5.0   2018-11-14 [1] CRAN (R 3.5.2)
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.2)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.2)
 processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.2)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
 R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.2)
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.2)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.2)
 rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
 usethis     * 1.4.0   2018-08-14 [1] CRAN (R 3.5.2)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
```

By the way, it did work fine on my colleague's Mac.
Thanks

**Comment by hrbrmstr** [comment]
thx. Lemme get 3.5.2 onto the Windows VM (the Rtools for that are definitely different) and I'll get back to you ASAP.

**Comment by aecoleman** [comment]
Similar issue on R 3.5.2 in Windows 10. I was able to install commit `f1759d8` using `devtools::install_github("hrbrmstr/msgxtractr", ref = 'f1759d8')`, but `2dc605b` and `017d6c0` both failed. I did not try `6535edc` or `6769a39`. Hopefully that is helps you narrow down what the issue may be.

**Comment by aecoleman** [comment]
I believe this is now fixed. I was just able to install it on the same machine that failed before, although it is now using R 3.6.0 (so not exactly the same config).

**Comment by f527** [comment]
Hello,

I am also unable to install.

OS: Win10 Enterprise, 64-bit
R version: 3.6.0
Devtools35

`devtools::install_github("hrbrmstr/msgxtractr")`
`Downloading GitHub repo hrbrmstr/msgxtractr@master`
`/Rtools/bin/tar: Child returned status 127`
`/Rtools/bin/tar: Error is not recoverable: exiting now`
`External tar failed with --force-local, trying without`
`/Rtools/bin/tar: Child returned status 127`
`/Rtools/bin/tar: Error is not recoverable: exiting now`
`External tar failed with --force-local, trying without`
`Error: Failed to install 'msgxtractr' from GitHub:`
`  Does not appear to be an R package (no DESCRIPTION)`
`In addition: Warning messages:`
`1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\<USER>\AppData\Local\Temp\RtmpIXPEtg\file39641a2bbb.tar.gz" -C "C:/Users/<USER>/AppData/Local/Temp/RtmpIXPEtg/remotes396417b329d0"’ returned error code 2`
`2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\<USER>\AppData\Local\Temp\RtmpIXPEtg\file39641a2bbb.tar.gz"' had status 2`

**Comment by hrbrmstr** [comment]
Those are not `msgxtractr`-related errors, those are Rtools-ish errors on Windows. Please take it up with  GitHub (transmission errors?) / or R-Core/CRAN.

**Comment by f527** [comment]
@hrbrmstr thanks for the quick response.  

I tried installing on my Linux machine (Ubuntu 19.10; RStudio 3.6.0) and got a bit further but still failed:

```
devtools::install_github("hrbrmstr/msgxtractr")
Downloading GitHub repo hrbrmstr/msgxtractr@master
✔  checking for file ‘/tmp/RtmpCDwxkk/remotes2fce3d7c336c/hrbrmstr-msgxtractr-c705017/DESCRIPTION’ ...
─  preparing ‘msgxtractr’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘msgxtractr_0.2.1.tar.gz’
   
Installing package into ‘/home/USER/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘msgxtractr’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/USER/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-VjHo9C/r-base-3.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/USER/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-VjHo9C/r-base-3.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c alloc.c -o alloc.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG  -I"/home/USER/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-VjHo9C/r-base-3.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c date.c -o date.o
In file included from date.c:33:
util.h:65:8: error: unknown type name ‘uint32_t’
 extern uint32_t GETINT32(unsigned char*p);
        ^~~~~~~~
util.h:66:8: error: unknown type name ‘uint16_t’
 extern uint16_t GETINT16(unsigned char*p);
        ^~~~~~~~
util.h:67:8: error: unknown type name ‘uint8_t’
 extern uint8_t GETINT8(unsigned char*p);
        ^~~~~~~
util.h:70:8: error: unknown type name ‘uint32_t’
 extern uint32_t geti32(FILE *fp);
        ^~~~~~~~
util.h:71:8: error: unknown type name ‘uint16_t’
 extern uint16_t geti16(FILE *fp);
        ^~~~~~~~
util.h:72:8: error: unknown type name ‘uint8_t’
 extern uint8_t geti8(FILE *fp);
        ^~~~~~~
make: *** [/usr/lib/R/etc/Makeconf:167: date.o] Error 1
ERROR: compilation failed for package ‘msgxtractr’
* removing ‘/home/USER/R/x86_64-pc-linux-gnu-library/3.6/msgxtractr’
Error: Failed to install 'msgxtractr' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpCDwxkk/file2fce213915a9/msgxtractr_0.2.1.tar.gz’ had non-zero exit status
```

**Comment by hrbrmstr** [comment]
See if what I just pushed fixes that issue.
